measurement_simulator:
  ros__parameters:
    measurement_noise_std: 0.1
    pub_rate: 10.0
    use_sim_time: True
trajectory_simulator:
  ros__parameters:
    load_trajectory: True
    same_trajectory: True
    trajectory_name: "trajectory_identical_drift2"
    total_steps: 100
    pub_rate: 10.0
    use_sim_time: True
    uav_origin: [0.0, 0.0, 2.0]
    ground_vehicle_origin: [0.0, 0.0, 0.0]
    anchors:
      a1:
        id: "0x0009D6" 
        position: [-0.32, 0.3, 0.875]
      a2:
        id: "0x0009E5"
        position: [0.32, -0.3, 0.875]
      a3:
        id: "0x0016FA" 
        position: [0.32, 0.3, 0.33]
      a4:
        id: "0x0016CF"
        position: [-0.32, -0.3, 0.33]
    tags:
      t1: 
        id: "0x001155"
        position: [-0.24, -0.24, -0.06]
      t2: 
        id: "0x001397"
        position: [0.24, 0.24, -0.06]