agv_offboard_control:
  ros__parameters:
    offboard_control_mode_topic: "/px4_2/fmu/in/offboard_control_mode"
    velocity_setpoint_topic: "/px4_2/fmu/in/rover_velocity_setpoint"
    vehicle_command_topic: "/px4_2/fmu/in/vehicle_command"
    vehicle_odometry_topic: "/px4_2/fmu/out/vehicle_odometry"
    trajectory_csv_file: "/home/amarsil/radio_ws/trajectories_positions/trajectory_lemniscate_agv.csv"
    lookahead_distance: 2.0
    kp_v: 0.5
    kp_w: 0.25